<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tw</string>
	</array>
	<key>name</key>
	<string>Twee</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(&lt;html&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.block.punctuation.definition.html.begin.twee</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>text.html.twee</string>
			<key>end</key>
			<string>(&lt;/html&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.block.punctuation.definition.html.end.twee</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.html.twee</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^::)(.+)(\[)(stylesheet)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.twee</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.block.entity.name.type.css.twee</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment.block.punctuation.definition.tag.begin.twee</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.modifer.twee</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>comment.block.punctuation.definition.tag.end.twee</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.embeded.css.twee</string>
			<key>end</key>
			<string>^(?=::)</string>
			<key>name</key>
			<string>meta.css.twee</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^::)(.+)(\[)(script)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.twee</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.block.entity.name.type.js.twee</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment.block.punctuation.definition.tag.begin.twee</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.modifer.twee</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>comment.block.punctuation.definition.tag.end.twee</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.embeded.js.twee</string>
			<key>end</key>
			<string>^(?=::)</string>
			<key>name</key>
			<string>meta.js.twee</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.twee</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.class.passage.twee</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.passage.twee</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>comment.block.punctuation.definition.tag.begin.twee</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.twee</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>comment.block.punctuation.definition.tag.end.twee</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(^::)\s*((Start|StoryTitle|StorySubtitle|StoryAuthor|StoryMenu)|([^\[]*))\s*((\[)([^\]]*)(\]))*</string>
			<key>name</key>
			<string>meta.passage.twee</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;&lt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.block.punctuation.definition.function.begin.twee</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&gt;&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.block.punctuation.definition.function.end.twee</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.twee</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(back|choice|display|actions|pop|print|set|if|else|endif|remember|silently|endsilently)</string>
					<key>name</key>
					<string>keyword.control.twee</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\$\b([A-Za-z_][A-Za-z0-9_]*)\b</string>
					<key>name</key>
					<string>variable.parameter.twee</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(eq|neq|gt|gte|lt|lte|and|or|not)\b</string>
					<key>name</key>
					<string>keyword.operator.twee</string>
				</dict>
				<dict>
					<key>match</key>
					<string>('[^']*')</string>
					<key>name</key>
					<string>string.quoted.single.twee</string>
				</dict>
				<dict>
					<key>match</key>
					<string>("[^"]*")</string>
					<key>name</key>
					<string>string.quoted.double.twee</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(/[^/]*/)</string>
					<key>name</key>
					<string>string.regexp.twee</string>
				</dict>
				<dict>
					<key>match</key>
					<string>!|%|&amp;|\*|\-\-|\-|\+\+|\+|~|===|==|=|!=|!==|&lt;=|&gt;=|&lt;&lt;=|&gt;&gt;=|&gt;&gt;&gt;=|&lt;&gt;|&lt;|&gt;|!|&amp;&amp;|\|\||\?\:|\*=|(?&lt;!\()/=|%=|\+=|\-=|&amp;=|\^=|\b(in|instanceof|new|delete|typeof|void)\b</string>
					<key>name</key>
					<string>keyword.operator.js</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b((0(x|X)[0-9a-fA-F]+)|([0-9]+(\.[0-9]+)?))\b</string>
					<key>name</key>
					<string>constant.numeric.js</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\btrue\b</string>
					<key>name</key>
					<string>constant.language.boolean.true.js</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bfalse\b</string>
					<key>name</key>
					<string>constant.language.boolean.false.js</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bnull\b</string>
					<key>name</key>
					<string>constant.language.null.js</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(Infinity|NaN|undefined)\b</string>
					<key>name</key>
					<string>constant.language.js</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.block.punctuation.definition.link.begin.twee</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.link.twee</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment.block.punctuation.definition.link.end.twee</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\[\[)([^\]]*)(\]\])</string>
			<key>name</key>
			<string>meta.markup.underline.link.twee</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.twee</string>
	<key>uuid</key>
	<string>a30284bd-5e16-49c8-9855-e095bcfe9c51</string>
</dict>
</plist>
